// examples/vue-thumbnail/src/App.vue
<script setup lang="ts">
import { makePersistedAdapter } from '@livestore/adapter-web'
import LiveStoreSharedWorker from '@livestore/adapter-web/shared-worker?sharedworker'
import { LiveStoreProvider } from 'vue-livestore'

import { schema } from './livestore/schema.ts'
import LiveStoreWorker from './livestore.worker.ts?worker'
import Gallery from './components/Gallery.vue'
import FileSyncProvider from './components/FileSyncProvider.vue'
import SyncStatus from './components/SyncStatus.vue'

// Allow storeId to be set via query param for testing isolation
const urlParams = new URLSearchParams(window.location.search)
// Bump default storeId when schema changes to avoid loading an incompatible persisted db in dev.
const storeId = urlParams.get('storeId') || 'vue_thumbnail_store_v1'

const adapter = makePersistedAdapter({
  storage: { type: 'opfs' },
  worker: LiveStoreWorker,
  sharedWorker: LiveStoreSharedWorker,
})

const authToken = import.meta.env.VITE_AUTH_TOKEN

const storeOptions = {
  schema,
  adapter,
  storeId,
  syncPayload: { authToken }
}

// Thumbnail worker URL - Vite handles bundling
const thumbnailWorkerUrl = new URL('./thumbnail.worker.ts', import.meta.url)
</script>

<template>
  <Suspense>
    <template #default>
      <LiveStoreProvider :options="storeOptions">
        <FileSyncProvider
          :auth-token="authToken"
          :thumbnails="{ workerUrl: thumbnailWorkerUrl }"
        >
          <div class="layout">
            <div class="main">
              <Gallery />
            </div>
            <SyncStatus />
          </div>
        </FileSyncProvider>
      </LiveStoreProvider>
    </template>
    <template #fallback>
      <div class="loading">Loading...</div>
    </template>
  </Suspense>
</template>

<style scoped>
.loading {
  padding: 2rem;
}

.layout {
  display: grid;
  grid-template-columns: 1fr 280px;
  height: 100vh;
}

.main {
  overflow-y: auto;
}
</style>

// examples/react-thumbnail/src/App.tsx
import { makePersistedAdapter } from "@livestore/adapter-web"
import LiveStoreSharedWorker from "@livestore/adapter-web/shared-worker?sharedworker"
import { storeOptions, StoreRegistry } from "@livestore/livestore"
import { StoreRegistryProvider } from "@livestore/react"
import { unstable_batchedUpdates as batchUpdates } from "react-dom"

import { FileSyncProvider } from "./components/FileSyncProvider.tsx"
import { Gallery } from "./components/Gallery.tsx"
import { SyncStatus } from "./components/SyncStatus.tsx"
import LiveStoreWorker from "./livestore.worker.ts?worker"
import { schema, SyncPayload } from "./livestore/schema.ts"

// Allow storeId to be set via query param for testing isolation
const urlParams = new URLSearchParams(window.location.search)
// Bump default storeId when schema changes to avoid loading an incompatible persisted db in dev.
const storeId = urlParams.get("storeId") || "react_thumbnail_store_v1"

const adapter = makePersistedAdapter({
  storage: { type: "opfs" },
  worker: LiveStoreWorker,
  sharedWorker: LiveStoreSharedWorker
})

const authToken = import.meta.env.VITE_AUTH_TOKEN as string

const syncPayload = { authToken }

// Auth headers for file sync API
const getAuthHeaders = () => ({
  Authorization: `Bearer ${authToken}`
})

const storeRegistry = new StoreRegistry({ defaultOptions: { batchUpdates } })

// Thumbnail worker URL - Vite handles bundling (uses canvas processor)
const thumbnailWorkerUrl = new URL("./thumbnail.worker.ts", import.meta.url)

export const reactStoreOptions = storeOptions({
  schema,
  adapter,
  storeId,
  syncPayloadSchema: SyncPayload,
  syncPayload
})

export const App = () => (
  <StoreRegistryProvider storeRegistry={storeRegistry}>
    <FileSyncProvider
      authHeaders={getAuthHeaders}
      authToken={authToken}
      thumbnails={{ workerUrl: thumbnailWorkerUrl }}
    >
      <div className="app-layout">
        <div className="main">
          <Gallery />
        </div>
        <SyncStatus />
      </div>
    </FileSyncProvider>
  </StoreRegistryProvider>
)
