// examples/vue-thumbnail/src/components/FileSyncProvider.vue
<script setup lang="ts">
import { onUnmounted } from 'vue'
import { useStore } from 'vue-livestore'
import { initFileSync } from '@livestore-filesync/core'
import { layer as opfsLayer } from '@livestore-filesync/opfs'

const props = defineProps<{
  signerBaseUrl?: string
  headers?: Record<string, string>
  authToken?: string
}>()

const { store } = useStore()

const dispose = initFileSync(store, {
  fileSystem: opfsLayer(),
  remote: {
    signerBaseUrl: props.signerBaseUrl ?? '/api',
    headers: props.headers,
    authToken: props.authToken
  }
})

onUnmounted(() => {
  void dispose()
})
</script>

<template>
  <slot />
</template>

// examples/react-filesync/src/components/FileSyncProvider.tsx
import { useEffect, type ReactNode } from "react";
import { useStore } from "@livestore/react";
import {
  disposeFileSync,
  initFileSync,
  startFileSync,
  stopFileSync,
} from "@livestore-filesync/core";
import { layer as opfsLayer } from "@livestore-filesync/opfs";

type FileSyncProviderProps = {
  signerBaseUrl?: string;
  headers?: Record<string, string>;
  authHeaders?: () => Record<string, string>;
  authToken?: string;
  children?: ReactNode;
};

export const FileSyncProvider = ({
  signerBaseUrl = "/api",
  headers,
  authHeaders,
  authToken,
  children,
}: FileSyncProviderProps) => {
  const { store } = useStore();

  const remote: {
    signerBaseUrl: string;
    headers?: Record<string, string>;
    authToken?: string;
  } = {
    signerBaseUrl,
  };

  const resolvedHeaders = headers ?? authHeaders?.();
  if (resolvedHeaders) {
    remote.headers = resolvedHeaders;
  }
  if (authToken) {
    remote.authToken = authToken;
  }

  initFileSync(store, {
    fileSystem: opfsLayer(),
    remote,
  });

  useEffect(() => {
    startFileSync();

    return () => {
      stopFileSync();
      void disposeFileSync();
    };
  }, [headers, authHeaders, authToken, signerBaseUrl, store]);

  return <>{children}</>;
};
