// examples/vue-filesync/src/components/Gallery.vue
<script setup lang="ts">
import { ref } from 'vue'
import { queryDb } from '@livestore/livestore'
import { useQuery } from 'vue-livestore'
import { isOnline, saveFile } from '@livestore-filesync/core'
import { tables } from '../livestore/schema.ts'
import ImageCard from './ImageCard.vue'

const inputRef = ref<HTMLInputElement | null>(null)

const files = useQuery(queryDb(tables.files.where({ deletedAt: null })))

const handleUploadClick = () => {
  inputRef.value?.click()
}

const handleFileChange = async (e: Event) => {
  const target = e.target as HTMLInputElement
  const selectedFiles = target.files
  if (!selectedFiles || selectedFiles.length === 0) return

  try {
    const savePromises = Array.from(selectedFiles).map((file) => saveFile(file))
    const results = await Promise.all(savePromises)
    console.log('Files saved:', results)
  } catch (error) {
    console.error('Failed to save files:', error)
  }

  // Reset input
  if (inputRef.value) {
    inputRef.value.value = ''
  }
}
</script>

<template>
  <div
    class="container"
    data-testid="gallery"
  >
    <div class="toolbar">
      <button
        type="button"
        @click="handleUploadClick"
        data-testid="upload-button"
      >
        + Upload Image
      </button>
      <input
        ref="inputRef"
        type="file"
        accept="image/*"
        multiple
        @change="handleFileChange"
        class="hidden"
        data-testid="file-input"
      />
      <div
        class="status"
        data-testid="status-indicator"
      >
        <span
          class="status-dot"
          :class="{ online: isOnline() }"
        />
        {{ isOnline() ? 'Online' : 'Offline' }}
      </div>
    </div>

    <div
      v-if="!files || files.length === 0"
      class="empty"
      data-testid="empty-state"
    >
      <p>No images yet. Upload one to get started!</p>
    </div>
    <div
      v-else
      class="layout"
    >
      <ImageCard
        v-for="file in files"
        :key="file.id"
        :file="file"
      />
    </div>
  </div>
</template>

<style scoped>
.container {
  padding: 1rem;
}

.toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 1rem;
  gap: 1rem;
  flex-wrap: wrap;
}

.hidden {
  display: none;
}

.status {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.status-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  background-color: #999;
}

.status-dot.online {
  background-color: #090;
}

.empty {
  padding: 3rem 1rem;
  text-align: center;
  color: #666;
}

.layout {
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}
</style>

// examples/react-filesync/src/components/Gallery.tsx
import React from "react";
import { queryDb } from "@livestore/livestore";
import { useStore } from "@livestore/react";
import { isOnline, saveFile } from "@livestore-filesync/core";
import { tables } from "../livestore/schema.ts";
import { ImageCard } from "./ImageCard.tsx";

export const Gallery: React.FC = () => {
  const { store } = useStore();
  const inputRef = React.useRef<HTMLInputElement | null>(null);

  const files = store.useQuery(
    queryDb(tables.files.where({ deletedAt: null }))
  );

  const handleUploadClick = () => {
    inputRef.current?.click();
  };

  const handleFileChange = async (
    event: React.ChangeEvent<HTMLInputElement>
  ) => {
    const selectedFiles = event.target.files;
    if (!selectedFiles || selectedFiles.length === 0) return;

    try {
      const savePromises = Array.from(selectedFiles).map((file) => saveFile(file));
      const results = await Promise.all(savePromises);
      console.log("Files saved:", results);
    } catch (error) {
      console.error("Failed to save files:", error);
    }

    if (inputRef.current) {
      inputRef.current.value = "";
    }
  };

  return (
    <div className="container" data-testid="gallery">
      <div className="toolbar">
        <button
          type="button"
          onClick={handleUploadClick}
          data-testid="upload-button"
        >
          + Upload Image
        </button>
        <input
          ref={inputRef}
          type="file"
          accept="image/*"
          multiple
          onChange={handleFileChange}
          className="hidden"
          data-testid="file-input"
        />
        <div className="status" data-testid="status-indicator">
          <span
            className={`status-dot${isOnline() ? " online" : ""}`}
          />
          {isOnline() ? "Online" : "Offline"}
        </div>
      </div>

      {!files || files.length === 0 ? (
        <div className="empty" data-testid="empty-state">
          <p>No images yet. Upload one to get started!</p>
        </div>
      ) : (
        <div className="layout">
          {files.map((file) => (
            <ImageCard key={file.id} file={file} />
          ))}
        </div>
      )}
    </div>
  );
};
