// examples/react-filesync/src/App.tsx
import { makePersistedAdapter } from '@livestore/adapter-web'
import LiveStoreSharedWorker from '@livestore/adapter-web/shared-worker?sharedworker'
import { LiveStoreProvider } from '@livestore/react'
import { unstable_batchedUpdates as batchUpdates } from 'react-dom'

import { schema, SyncPayload } from './livestore/schema.ts'
import LiveStoreWorker from './livestore.worker.ts?worker'
import { Gallery } from './components/Gallery.tsx'
import { FileSyncProvider } from './components/FileSyncProvider.tsx'

// Allow storeId to be set via query param for testing isolation
const urlParams = new URLSearchParams(window.location.search)
const storeId = urlParams.get('storeId') || 'react_filesync_store'

const adapter = makePersistedAdapter({
  storage: { type: 'opfs' },
  worker: LiveStoreWorker,
  sharedWorker: LiveStoreSharedWorker,
})

const authToken = import.meta.env.VITE_AUTH_TOKEN

const syncPayload = { authToken }

// Auth headers for file sync API
const getAuthHeaders = () => ({
  Authorization: `Bearer ${authToken}`,
})

export const App = () => (
  <LiveStoreProvider
    schema={schema}
    adapter={adapter}
    storeId={storeId}
    syncPayloadSchema={SyncPayload}
    syncPayload={syncPayload}
    renderLoading={() => <div className="loading">Loading...</div>}
    batchUpdates={batchUpdates}
  >
    <FileSyncProvider authHeaders={getAuthHeaders}>
      <Gallery />
    </FileSyncProvider>
  </LiveStoreProvider>
)

// examples/vue-filesync/src/App.vue
<script setup lang="ts">
import { makePersistedAdapter } from '@livestore/adapter-web'
import LiveStoreSharedWorker from '@livestore/adapter-web/shared-worker?sharedworker'
import { LiveStoreProvider } from 'vue-livestore'
import { FileSyncProvider } from '@livestore-filesync/vue'

import { schema } from './livestore/schema.ts'
import LiveStoreWorker from './livestore.worker.ts?worker'
import Gallery from './components/Gallery.vue'

// Allow storeId to be set via query param for testing isolation
const urlParams = new URLSearchParams(window.location.search)
const storeId = urlParams.get('storeId') || 'vue_filesync_store'

const adapter = makePersistedAdapter({
  storage: { type: 'opfs' },
  worker: LiveStoreWorker,
  sharedWorker: LiveStoreSharedWorker,
})

const authToken = import.meta.env.VITE_AUTH_TOKEN

const storeOptions = {
  schema,
  adapter,
  storeId,
  syncPayload: { authToken }
}

// Auth headers for file sync API
const getAuthHeaders = () => ({
  'Authorization': `Bearer ${authToken}`,
})
</script>

<template>
  <Suspense>
    <template #default>
      <LiveStoreProvider :options="storeOptions">
        <FileSyncProvider :auth-headers="getAuthHeaders">
          <Gallery />
        </FileSyncProvider>
      </LiveStoreProvider>
    </template>
    <template #fallback>
      <div>Loading LiveStore...</div>
    </template>
  </Suspense>
</template>
